//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.12 at 11:07:35 AM BDT 
//


package com.srbd.jaxbsrc;

import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for apiobjectlist complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="apiobjectlist">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="apiobject" type="{}apiobject" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "apiobjectlist", propOrder = {
    "apiobject"
})
public class Apiobjectlist {

    @XmlElement(required = true)
    protected List<Apiobject> apiobject;

    /**
     * Gets the value of the apiobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apiobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApiobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Apiobject }
     * 
     * 
     */
    public List<Apiobject> getApiobject() {
        if (apiobject == null) {
            apiobject = new ArrayList<Apiobject>();
        }
        return this.apiobject;
    }
    
    @Override
    public String toString() {
    	List<Apiobject> l = getApiobject();
    	String ret = "";
    	for (Apiobject apiobject : l) {
    		
    		ret = ret + apiobject.objectname + ": ";
    		List<String>apis = apiobject.getApi();
    		for (String string : apis) {
    			
    			ret = ret + string+"\t";
			}
    		ret += "\n";
		}
    	return ret;
    }

}
