//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.12 at 11:07:35 AM BDT 
//


package com.srbd.jaxbsrc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hello package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Apiobjectcollection_QNAME = new QName("", "apiobjectcollection");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hello
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Apiobjectlist }
     * 
     */
    public Apiobjectlist createApiobjectlist() {
        return new Apiobjectlist();
    }

    /**
     * Create an instance of {@link Apiobject }
     * 
     */
    public Apiobject createApiobject() {
        return new Apiobject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Apiobjectlist }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "apiobjectcollection")
    public JAXBElement<Apiobjectlist> createApiobjectcollection(Apiobjectlist value) {
        return new JAXBElement<Apiobjectlist>(_Apiobjectcollection_QNAME, Apiobjectlist.class, null, value);
    }

}
